name: "Deploy - On branch main/release Push"
on:
  push:
    branches:
      - main
      - 'releases/**'

concurrency: ${{ github.repository }}
jobs:
  Deploy:
    uses: MOV-AI/.github/.github/workflows/ros-workflow.yml@v2.3
    with:
      deploy: true
      ros_distro: '["noetic"]'
      run_catkin_tests: true
      install_test: true
    secrets:
      auto_commit_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      auto_commit_mail: ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
      auto_commit_pwd: ${{ secrets.RAISE_BOT_COMMIT_PASSWORD }}
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      nexus_publisher_user: ${{ secrets.NEXUS_PUBLISHER_USR }}
      nexus_publisher_password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
      aws_sqs_rosdep_access_key: ${{ secrets.AWS_SQS_ROSDEP_ACCESS_KEY }}
      aws_sqs_rosdep_secret_access_key: ${{ secrets.AWS_SQS_ROSDEP_SECRET_ACCESS_KEY }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      proxmox_ve_sim_username: ${{ secrets.PROXMOX_MARVIN_VE_USERNAME }}
      proxmox_ve_sim_password: ${{ secrets.PROXMOX_MARVIN_VE_PASSWORD }}
      ssh_priv_key: ${{ secrets.SSH_PEM_AWS_SLAVE }}
      slack_token_id: ${{ secrets.SLACK_TOKEN_ID }}

